smb.sharefolder = "/home/murzin"
smb.confdir = "/etc/samba/conf"
smb.rootconf = "/etc/samba/conf/root.conf"
smb.restartscript = "/etc/samba/restart"
domain.userlist = "/home/murzin/java_grails_programming/workspace/domain_users.txt"
domain.grouplist = "/home/murzin/java_grails_programming/workspace/domain_groups.txt"
quota.setscript = "/etc/samba/setquota"
quota.fstype = "zfs"